version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: lumen-docker
    ports:
    - 9090:80
    volumes:
    - .:/srv/app
    links:
    - mysql
    - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: lumen_docker
      DB_USERNAME: panda
      DB_PASSWORD: hellorcpworld
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    ports:
    - 13306:3306
    environment:
      MYSQL_DATABASE: lumen_docker
      MYSQL_USER: panda
      MYSQL_PASSWORD: hellorcpworld
      MYSQL_ROOT_PASSWORD: icantbelieveyouvedonethis
  redis:
    image: redis:4.0-alpine
    ports:
    - 16379:6379
